# Generated by Django 3.0.3 on 2020-12-25 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='path',
        ),
        migrations.AddField(
            model_name='video',
            name='file',
            field=models.FileField(default='some_path', upload_to='documents/'),
        ),
    ]
