# Generated by Django 3.0.3 on 2020-12-25 20:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('streamer', '0002_auto_20201225_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(default='some_path', upload_to=''),
        ),
    ]
